### ISSUE TITLE
hello, did you get the timestamp?or something else ?in smb share exe 

### ISSUE THREAD

**Issue by Carnival-z** [F41zK4r1m/HackTheBox#1]
i get a timestamp but don't working

**Comment by F41zK4r1m** [comment]
Hi @Carnival-z,

In which box exactly you were referring for the timestamp or smb share.exe?

**Comment by Carnival-z** [comment]
i found it int path \Temporary Projects\  there are have something you missing? a Exe  and a file enc。enc look like a encryption file。and exe alse have the key iv about timestamp . every thing look like ok？but the enc file doesnot working .i donot know whatt happend

**Comment by F41zK4r1m** [comment]
I checked the .Exe in the PSpy & as you mentioned it took the timestamp for the encryption of the file.
I am also trying to figure out for the decryption of the file, I'll update my walkthrough accordingly after the decryption.
